VERSION="0008_school_management_finance_library"
def apply(con):
    con.executescript("""
    CREATE TABLE IF NOT EXISTS student_enrollment_history(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL,session_id INTEGER,level_name TEXT NOT NULL,class_id INTEGER,enrolled_at TEXT,completed_at TEXT,active INTEGER NOT NULL DEFAULT 1,notes TEXT,created_at TEXT NOT NULL,FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE,FOREIGN KEY(session_id) REFERENCES academic_sessions(id),FOREIGN KEY(class_id) REFERENCES school_classes(id));
    CREATE INDEX IF NOT EXISTS idx_student_history_student ON student_enrollment_history(student_id,session_id);
    CREATE TABLE IF NOT EXISTS finance_fee_assessments(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL,session_id INTEGER NOT NULL,category TEXT NOT NULL,amount REAL NOT NULL,due_date TEXT,notes TEXT,created_by INTEGER,created_at TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE,FOREIGN KEY(session_id) REFERENCES academic_sessions(id),FOREIGN KEY(created_by) REFERENCES admins(id));
    CREATE TABLE IF NOT EXISTS finance_payments(id INTEGER PRIMARY KEY AUTOINCREMENT,receipt_no TEXT UNIQUE NOT NULL,student_id INTEGER NOT NULL,session_id INTEGER NOT NULL,amount REAL NOT NULL,category TEXT NOT NULL,method TEXT NOT NULL,reference TEXT,paid_at TEXT NOT NULL,recorded_by INTEGER NOT NULL,status TEXT NOT NULL DEFAULT "posted",notes TEXT,created_at TEXT NOT NULL,FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE,FOREIGN KEY(session_id) REFERENCES academic_sessions(id),FOREIGN KEY(recorded_by) REFERENCES admins(id));
    CREATE INDEX IF NOT EXISTS idx_finance_payments_recorded_by ON finance_payments(recorded_by,paid_at);
    CREATE INDEX IF NOT EXISTS idx_finance_payments_student ON finance_payments(student_id,session_id,paid_at);
    CREATE TABLE IF NOT EXISTS finance_delivery_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,payment_id INTEGER NOT NULL,channel TEXT NOT NULL,recipient TEXT,status TEXT NOT NULL,provider_reference TEXT,error_message TEXT,sent_by INTEGER,sent_at TEXT NOT NULL,FOREIGN KEY(payment_id) REFERENCES finance_payments(id) ON DELETE CASCADE,FOREIGN KEY(sent_by) REFERENCES admins(id));
    CREATE TABLE IF NOT EXISTS library_books(id INTEGER PRIMARY KEY AUTOINCREMENT,isbn TEXT,title TEXT NOT NULL,author TEXT,publisher TEXT,publication_year INTEGER,category TEXT,shelf TEXT,total_copies INTEGER NOT NULL DEFAULT 1,available_copies INTEGER NOT NULL DEFAULT 1,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,created_by INTEGER,FOREIGN KEY(created_by) REFERENCES admins(id));
    CREATE TABLE IF NOT EXISTS library_loans(id INTEGER PRIMARY KEY AUTOINCREMENT,book_id INTEGER NOT NULL,member_type TEXT NOT NULL,member_id INTEGER NOT NULL,borrowed_at TEXT NOT NULL,due_at TEXT,returned_at TEXT,status TEXT NOT NULL DEFAULT "borrowed",notes TEXT,issued_by INTEGER,received_by INTEGER,FOREIGN KEY(book_id) REFERENCES library_books(id),FOREIGN KEY(issued_by) REFERENCES admins(id),FOREIGN KEY(received_by) REFERENCES admins(id));
    CREATE INDEX IF NOT EXISTS idx_library_loans_member ON library_loans(member_type,member_id,status);
    CREATE INDEX IF NOT EXISTS idx_library_loans_book ON library_loans(book_id,status);
    """)
    rows=con.execute("SELECT se.student_id,se.session_id,se.class_id,c.name,COALESCE(se.enrolled_at,datetime('now')) FROM student_enrolments se JOIN school_classes c ON c.id=se.class_id LEFT JOIN student_enrollment_history h ON h.student_id=se.student_id AND h.session_id=se.session_id WHERE h.id IS NULL").fetchall()
    for r in rows: con.execute("INSERT INTO student_enrollment_history(student_id,session_id,level_name,class_id,enrolled_at,active,created_at) VALUES(?,?,?,?,?,1,?)",(r[0],r[1],r[3],r[2],r[4],r[4]))
    con.commit()
